### PR TITLE
GitHub Pages Site

### PR DESCRIPTION
**Pull request by mimiflynn**

### CODE REVIEW

**Comment by mimiflynn** [comment]
See screenshot below, and please note the `Background` and `Alternatives` sections need to be filled out.

image

**Comment by mimiflynn** [comment]
Documentation page on `Use`:

image

**Comment by mimiflynn** [comment]
Documentation page on `Development`:

image

**Comment by psmulovics** [comment]
This looks really awesome - thank you!

**Comment by kruplm** [comment]
The new design looks amazing thank you @mimiflynn! :) Can't wait to merge this.

**Comment by psmulovics** [comment]
@mimiflynn , so we only need content for background and alternatives? How about merging it as it is, and in a separate PR we would add those content?

**Comment by mimiflynn** [comment]
@psmulovics Sounds good, although I feel it would be best to add the content to this PR, I'll leave that to the team.

**Comment by psmulovics** [comment]
Let us try whether we can add a commit to this PR, @kruplm , @zkrobi

**Comment by kruplm** [comment]
> Let us try whether we can add a commit to this PR, @kruplm , @ZKRobi

Hi @mimiflynn and @psmulovics 
We can easily add commits to this PR if we check it out. :)
Let me look into the necessary documentation files.

**Comment by mimiflynn** [comment]
I made a couple updates. Looks good! Ready for review.

**Review by psmulovics — APPROVED** [review]

**Pull request merged**
