### PR TITLE
Versioning tag

### PR DESCRIPTION
**Pull request by pkErbynn**

### CODE REVIEW

**Review by psmulovics — CHANGES_REQUESTED** [review]
Can we move this to GitVersion instead of manual versioning?

@BalassaMarton might be able to help, his similar file is at https://github.com/morganstanley/dotnet-please/blob/main/GitVersion.yml and at https://github.com/morganstanley/dotnet-please/blob/main/DotNetPlease/DotNetPlease.csproj#L27-L30

**Comment by psmulovics** [comment]
You still seem to missing the GitVersion.yml and the package

**Comment by psmulovics** [comment]
And the csproj (like https://github.com/morganstanley/dotnet-please/blob/main/DotNetPlease/DotNetPlease.csproj#L27-L30 )

**Comment by pkErbynn** [comment]
pr updated with required files

**Review by psmulovics — APPROVED** [review]

**Comment by BalassaMarton** [comment]
You need to set fetch-depth on the checkout action:
https://github.com/morganstanley/dotnet-please/blob/main/.github/workflows/build.yml#L14
GitVersion needs the whole commit history of the branch being built, as explained here:
https://gitversion.net/docs/reference/requirements

**Review by psmulovics — DISMISSED** [review]

**Comment by pkErbynn** [comment]
@BalassaMarton @bagdxk kindly review my pr and give me feedback. thank you

**Comment by BalassaMarton** [comment]
> @BalassaMarton @bagdxk kindly review my pr and give me feedback. thank you

TBH I'm not sure what would happen, but since we're not publishing the packages, we can run this without risk.

**Comment by psmulovics** [comment]
So they are trying to replicate the setup from Please here for versioning and release to nuge.org.

**Pull request closed without merging**
